# Leitura inicial do CSV

In [ ]:
import pandas as pd

base_dir = 'C:/Users/gabri/OneDrive/Área de Trabalho/joao/TB/medicamentos-fdcc/tasks/analise-inicial-csv-e-api'
csv_path = f'{base_dir}/docs/inputs/consulta-contratacoes-20260930162835.csv'


CSV = pd.read_csv(csv_path, sep=';', encoding='utf-8', dtype=str)
CSV

,Número de Controle PNCP da Contratação,Número Sequencial da Contratação,Número da Contratação,Ano da Contratação,Código da Situação da Contratação,Nome da Situação da Contratação,CNPJ do Órgão/Entidade da Contratação,Razão Social do Órgão/Entidade da Contratação,Código do Poder do Órgão/Entidade,Nome do Poder do Órgão/Entidade,...,Indicador de existência de Resultado,Indicador de existência de Ata de Registro de Preço vinculada,Indicador de existência de Contrato/Empenho vinculado,Data de Publicação no PNCP,Data da última atualização no PNCP,Id do usuário da plataforma que publicou/atualizou a Contratação,Nome do usuário da plataforma que publicou/atualizou a Contratação,Link para detalhamento da Contratação no Portal,Link plataforma de origem,Link Processo Eletrônico
0,03277610000125-1-000512/2026,512,357,2026,1,Divulgada no PNCP,03277610000125,MINISTERIO DA DEFESA,E,Executivo,...,não,não,não,30/09/2026,30/09/2026,3,Compras.gov.br,https://pncp.estaleiro.serpro.gov.br/compras/0...,https://cnetmobile.estaleiro.serpro.gov.br/com...,https://super.defesa.gov.br/sei/modulos/pesqui...
1,00394502000144-1-012741/2026,12741,108,2026,1,Divulgada no PNCP,00394502000144,COMANDO DA MARINHA,E,Executivo,...,sim,não,não,30/09/2026,30/09/2026,3,Compras.gov.br,https://pncp.estaleiro.serpro.gov.br/compras/0...,NaN,https://pncp.gov.br/app/editais
2,00038174000143-1-000144/2026,144,90024,2026,1,Divulgada no PNCP,00038174000143,FUNDACAO UNIVERSIDADE DE BRASILIA,E,Executivo,...,sim,não,não,16/06/2026,30/09/2026,3,Compras.gov.br,https://pncp.estaleiro.serpro.gov.br/compras/0...,https://cnetmobile.estaleiro.serpro.gov.br/com...,NaN
3,08302402000152-1-000037/2026,37,40,2026,1,Divulgada no PNCP,08302402000152,INSTITUTO DE ASSISTENCIA A SAUDE DOS SERVIDORE...,E,Executivo,...,não,não,não,30/09/2026,30/09/2026,3,Compras.gov.br,https://pncp.estaleiro.serpro.gov.br/compras/0...,https://cnetmobile.estaleiro.serpro.gov.br/com...,https://sei.df.gov.br/sei
4,33654831000136-1-000025/2026,25,44,2026,1,Divulgada no PNCP,33654831000136,CONSELHO NACIONAL DE DESENVOLVIMENTO CIENTIFIC...,E,Executivo,...,não,não,não,30/09/2026,30/09/2026,3,Compras.gov.br,https://pncp.estaleiro.serpro.gov.br/compras/3...,https://cnetmobile.estaleiro.serpro.gov.br/com...,https://sei.cnpq.br/sei
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1510,08942610000116-1-000006/2026,6,6,2026,1,Divulgada no PNCP,08942610000116,POLICIA MILITAR DO DISTRITO FEDERAL,E,Executivo,...,sim,não,não,29/01/2025,29/01/2025,3,Compras.gov.br,https://pncp.estaleiro.serpro.gov.br/compras/0...,NaN,NaN
1511,08942610000116-1-000005/2026,5,5,2026,1,Divulgada no PNCP,08942610000116,POLICIA MILITAR DO DISTRITO FEDERAL,E,Executivo,...,sim,não,não,29/01/2025,29/01/2025,3,Compras.gov.br,https://pncp.estaleiro.serpro.gov.br/compras/0...,NaN,NaN
1512,08942610000116-1-000004/2026,4,2,2026,1,Divulgada no PNCP,08942610000116,POLICIA MILITAR DO DISTRITO FEDERAL,E,Executivo,...,sim,não,não,29/01/2025,29/01/2025,3,Compras.gov.br,https://pncp.estaleiro.serpro.gov.br/compras/0...,NaN,NaN
1513,08942610000116-1-000003/2026,3,3,2026,1,Divulgada no PNCP,08942610000116,POLICIA MILITAR DO DISTRITO FEDERAL,E,Executivo,...,sim,não,não,29/01/2025,29/01/2025,3,Compras.gov.br,https://pncp.estaleiro.serpro.gov.br/compras/0...,NaN,NaN
1514,08942610000116-1-000001/2026,1,1,2026,1,Divulgada no PNCP,08942610000116,POLICIA MILITAR DO DISTRITO FEDERAL,E,Executivo,...,não,não,não,17/01/2025,17/01/2025,3,Compras.gov.br,https://pncp.estaleiro.serpro.gov.br/compras/0...,NaN,NaN

In [3]:
DF_EXEMPLO = CSV[
    (CSV['CNPJ do Órgão/Entidade da Contratação'] == '00394700000108')
    # & (CSV['Data de Publicação no PNCP'] == '30/09/2026')
].copy()
DF_EXEMPLO

,Número de Controle PNCP da Contratação,Número Sequencial da Contratação,Número da Contratação,Ano da Contratação,Código da Situação da Contratação,Nome da Situação da Contratação,CNPJ do Órgão/Entidade da Contratação,Razão Social do Órgão/Entidade da Contratação,Código do Poder do Órgão/Entidade,Nome do Poder do Órgão/Entidade,...,Indicador de existência de Resultado,Indicador de existência de Ata de Registro de Preço vinculada,Indicador de existência de Contrato/Empenho vinculado,Data de Publicação no PNCP,Data da última atualização no PNCP,Id do usuário da plataforma que publicou/atualizou a Contratação,Nome do usuário da plataforma que publicou/atualizou a Contratação,Link para detalhamento da Contratação no Portal,Link plataforma de origem,Link Processo Eletrônico
7,00394700000108-1-000411/2026,411,215,2026,1,Divulgada no PNCP,00394700000108,DISTRITO FEDERAL SECRETARIA DE SAUDE,E,Executivo,...,não,não,não,30/09/2026,30/09/2026,3,Compras.gov.br,https://pncp.estaleiro.serpro.gov.br/compras/0...,https://cnetmobile.estaleiro.serpro.gov.br/com...,http://sei.df.gov.br/sei/controlador.php?acao=...
14,00394700000108-1-000410/2026,410,212,2026,1,Divulgada no PNCP,00394700000108,DISTRITO FEDERAL SECRETARIA DE SAUDE,E,Executivo,...,não,não,não,29/09/2026,29/09/2026,3,Compras.gov.br,https://pncp.estaleiro.serpro.gov.br/compras/0...,https://cnetmobile.estaleiro.serpro.gov.br/com...,http://sei.df.gov.br/sei/controlador.php?acao=...
49,00394700000108-1-000400/2026,400,202,2026,1,Divulgada no PNCP,00394700000108,DISTRITO FEDERAL SECRETARIA DE SAUDE,E,Executivo,...,não,não,não,24/09/2026,24/09/2026,3,Compras.gov.br,https://pncp.estaleiro.serpro.gov.br/compras/0...,https://cnetmobile.estaleiro.serpro.gov.br/com...,http://sei.df.gov.br/sei/controlador.php?acao=...
99,00394700000108-1-000381/2026,381,183,2026,1,Divulgada no PNCP,00394700000108,DISTRITO FEDERAL SECRETARIA DE SAUDE,E,Executivo,...,não,não,não,17/09/2026,17/09/2026,3,Compras.gov.br,https://pncp.estaleiro.serpro.gov.br/compras/0...,https://cnetmobile.estaleiro.serpro.gov.br/com...,http://sei.df.gov.br/sei/controlador.php?acao=...
102,00394700000108-1-000379/2026,379,182,2026,1,Divulgada no PNCP,00394700000108,DISTRITO FEDERAL SECRETARIA DE SAUDE,E,Executivo,...,não,não,não,17/09/2026,17/09/2026,3,Compras.gov.br,https://pncp.estaleiro.serpro.gov.br/compras/0...,https://cnetmobile.estaleiro.serpro.gov.br/com...,http://sei.df.gov.br/sei/controlador.php?acao=...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1430,00394700000108-1-000016/2026,16,90011,2026,1,Divulgada no PNCP,00394700000108,DISTRITO FEDERAL SECRETARIA DE SAUDE,E,Executivo,...,sim,sim,não,21/01/2026,21/01/2026,3,Compras.gov.br,https://pncp.estaleiro.serpro.gov.br/compras/0...,https://cnetmobile.estaleiro.serpro.gov.br/com...,NaN
1434,00394700000108-1-000013/2026,13,90008,2026,1,Divulgada no PNCP,00394700000108,DISTRITO FEDERAL SECRETARIA DE SAUDE,E,Executivo,...,sim,sim,não,20/01/2026,20/01/2026,3,Compras.gov.br,https://pncp.estaleiro.serpro.gov.br/compras/0...,https://cnetmobile.estaleiro.serpro.gov.br/com...,NaN
1439,00394700000108-1-000008/2026,8,90004,2026,1,Divulgada no PNCP,00394700000108,DISTRITO FEDERAL SECRETARIA DE SAUDE,E,Executivo,...,sim,sim,não,19/01/2026,19/01/2026,3,Compras.gov.br,https://pncp.estaleiro.serpro.gov.br/compras/0...,https://cnetmobile.estaleiro.serpro.gov.br/com...,NaN
1449,00394700000108-1-000005/2026,5,90002,2026,1,Divulgada no PNCP,00394700000108,DISTRITO FEDERAL SECRETARIA DE SAUDE,E,Executivo,...,sim,não,não,15/01/2026,15/01/2026,3,Compras.gov.br,https://pncp.estaleiro.serpro.gov.br/compras/0...,https://cnetmobile.estaleiro.serpro.gov.br/com...,NaN
1458,00394700000108-1-000004/2026,4,90001,2026,1,Divulgada no PNCP,00394700000108,DISTRITO FEDERAL SECRETARIA DE SAUDE,E,Executivo,...,sim,sim,não,13/01/2026,13/01/2026,3,Compras.gov.br,https://pncp.estaleiro.serpro.gov.br/compras/0...,https://cnetmobile.estaleiro.serpro.gov.br/com...,NaN